services:
  registry-cache-docker.io:
    image: registry:2
    network_mode: bridge
    ports:
      - "5000:5000"
    environment:
      REGISTRY_PROXY_REMOTEURL: "https://registry-1.docker.io"
    volumes:
      - vol-docker.io:/var/lib/registry
    restart: always
  registry-cache-k8s.io:
    image: registry:2
    network_mode: bridge
    ports:
      - "5001:5000"
    environment:
      REGISTRY_PROXY_REMOTEURL: "https://registry.k8s.io"
    volumes:
      - vol-k8s.io:/var/lib/registry
    restart: always
  registry-cache-gcr.io:
    image: registry:2
    network_mode: bridge
    ports:
      - "5003:5000"
    environment:
      REGISTRY_PROXY_REMOTEURL: "https://gcr.io"
    volumes:
      - vol-gcr.io:/var/lib/registry
    restart: always
  registry-cache-ghcr.io:
    image: registry:2
    network_mode: bridge
    ports:
      - "5004:5000"
    environment:
      REGISTRY_PROXY_REMOTEURL: "https://ghcr.io"
    volumes:
      - vol-ghcr.io:/var/lib/registry
    restart: always

volumes:
  vol-docker.io:
  vol-k8s.io:
  vol-gcr.io:
  vol-ghcr.io:

#networks:
#  default:
#    name: cache-registries-network
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.31.0.0/24
#          gateway: 172.31.0.1
#      options:
#        com.docker.network.bridge.enable_icc: "true"
#        com.docker.network.bridge.enable_ip_masquerade: "true"
#        com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
#        com.docker.network.bridge.name: "docker0"
#        com.docker.network.driver.mtu: "1500"
