repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.89.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      # TODO: terramate fmt

  - repo: local
    hooks:
      - id: terramate_fmt
        name: Terramate fmt
        language: system
        entry: terramate fmt
        files: (.tm.hcl)$
