apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

# make sure the namespace exists
resources:
  - namespace.yaml

# rasterize this
helmCharts:
  - repo: https://charts.external-secrets.io
    name: external-secrets
    namespace: external-secrets
    version: 0.7.2
    includeCRDs: true
    valuesFile: values.yaml