---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: validation-secret
  namespace: secret-management
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-cluster-secret-store
  target:
    creationPolicy: Owner
  data:
    - secretKey: validation-secret
      remoteRef:
        key: validation-secret
        property: password
