apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  admin.enabled: "true"
  exec.enabled: "false"
  timeout.hard.reconciliation: 0s
  timeout.reconciliation: 180s
  kustomize.buildOptions: "--enable-helm"
