apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - gateway-class.yaml

patches:
  - patch: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: contour
        namespace: projectcontour
      data:
        # TODO: Make sure this doesn't conflict with anything else
        contour.yaml: |
          gateway:
            controllerName: projectcontour.io/gateway-controller
