apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: connect
    releaseName: onepassword-connect
    namespace: onepassword
    repo: https://1password.github.io/connect-helm-charts
    version: 1.11.0
    includeCRDs: true
