apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: "cilium"
    releaseName: "cilium"
    namespace: "kube-system"
    repo: "https://helm.cilium.io"
    version: "1.15.5"
    valuesInline:
      ipam:
        mode: "kubernetes"
      kubeProxyReplacement: true
      k8sServiceHost: "localhost"
      k8sServicePort: "7445"
      securityContext:
        # Only difference from talos documentation is the exclusion of `SYS_MODULE`
        capabilities:
          ciliumAgent:
            - "CHOWN"
            - "KILL"
            - "NET_ADMIN"
            - "NET_RAW"
            - "IPC_LOCK"
            - "SYS_ADMIN"
            - "SYS_RESOURCE"
            - "DAC_OVERRIDE"
          cleanCiliumState:
            - "NET_ADMIN"
            - "SYS_ADMIN"
            - "SYS_RESOURCE"
      cgroup:
        hostRoot: "/sys/fs/cgroup"
      gatewayAPI:
        enabled: true
