apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-issuer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-993"
spec:
  source:
    repoURL: https://github.com/ehakan/homelab.git
    targetRevision: HEAD
    path: kubernetes/apps/cluster-traffic/cluster-issuer/base
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  project: "default"


