apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateways
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-992"
spec:
  source:
    repoURL: https://github.com/ehakan/homelab.git
    targetRevision: HEAD
    path: kubernetes/apps/cluster-traffic/gateways/base
  destination:
    server: https://kubernetes.default.svc
    namespace: projectcontour
  project: "default"
