apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword-connect
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-995"
spec:
  source:
    repoURL: https://github.com/ehakan/homelab.git
    targetRevision: HEAD
    path: kubernetes/apps/cluster-secrets/onepassword-secret-store/base
  destination:
    server: https://kubernetes.default.svc
    namespace: onepassword
  project: "default"


