apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cf-ehakan-dev-dns-creds
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-secret-store
  data:
    - secretKey: api-token
      remoteRef:
        key: cf-ehakan-dev-dns
        property: credential
    - secretKey: zone-id
      remoteRef:
        key: cf-ehakan-dev-dns
        property: zone-id
    - secretKey: account-id
      remoteRef:
        key: cf-ehakan-dev-dns
        property: account-id



